dist: xenial
language: bash

before_install: # Download and install Terraform for us on the container (v0.15.5)
  - wget https://releases.hashicorp.com/terraform/0.15.5/terraform_0.15.5_linux_amd64.zip
  - unzip terraform_0.15.5_linux_amd64.zip
  - sudo mv terraform /usr/local/bin/
  - rm terraform_0.15.5_linux_amd64.zip

jobs:
  include:
    - stage: terraform plan # When a Pull Request is created - Validate our plan
      if: type IN (pull_request)
      script:
        - terraform init
        - terraform plan -out build.plan

    - stage: terraform apply # Merge our PR - Deploy it!
      if: type IN (push) and branch = main
      script:
        - terraform init
        - terraform plan -out build.plan
        - terraform apply build.plan

# Filter to only run this pipeline when it involves actions against the main branch
branches:
  only:
    - main