variable "app_name" {}
variable "env_prefix" {}
variable "instance_profile" {}
variable "ami_id" {}
variable "asg_desired_capacity" {}
variable "asg_max_size" {}
variable "asg_min_size" {}
variable "instance_type" {}
variable "internet_gateway" {}
variable "subnet_ids" {}
variable "app_security_group_id" {}
variable "elb_target_group" {}
variable "key_pair_name" {}