variable "app_name" {}
variable "env_prefix" {}
variable "vpc_cidr_block" {}
variable "subnet_cidr_block_1" {}
variable "subnet_cidr_block_2" {}
variable "avail_zone_1" {}
variable "avail_zone_2" {}
variable "instance_id_1" {}
variable "instance_id_2" {}